### ISSUE TITLE
Publish nuget package from Release build

### ISSUE THREAD

**Issue by hanabi1224** [richardschneider/peer-talk#38]
Just came accross the appveyor ci config and found that it publishes nuget package from Debug build, why not Release?

**Comment by richardschneider** [comment]
I was trying to get debugging info into Nuget so that dev's could debug this library from their own app.  Never succeeded and forgot to reset to Release build.

Feel free to fix.

**Comment by hanabi1224** [comment]
@richardschneider  just sent a PR to add sourcelink and symbol package (latest .snupkg which can be published to nuget)
